# ----------------------------
# Makefile Options
# ----------------------------

NAME=test

# Select option for Argument Processing at 'int main( int argc, char* argv[] )'
# 0: Simple Command Line Processing
# 1: Complex Command Line Processing - for Redirection & Quoting
LDHAS_ARG_PROCESSING = 0
LDHAS_EXIT_HANDLER = 1

# ----------------------------
#
include $(shell agondev-config --makefile)

